---

- name: dcn-vsc | _check-vm-status | Check the VSC VM is running
  become: yes
  virt:
    name: "{{ vsc_vm_name }}"
    command: status
    uri: qemu:///system
  register: vm_status
  ignore_errors: yes
