---

- name: dcn-vsc | _copy_image | copy image file to vsc node
  become: yes
  copy:
    src: "{{ playbook_dir }}/roles/dcn-vsc/files/{{ vsc_image_name }}.qcow2"
    dest: /tmp
    owner: root
    group: root
    mode: 0666

- name: dcn-vsc | _copy_image | get the md5sum of the qcow2 image
  shell: "md5sum /tmp/{{ vsc_image_name }}.qcow2"
  register: md5sum_result

- name: dcn-vsc | _copy_image | get the md5sum
  set_fact:
    vsc_md5sum: "{{ md5sum_result.stdout.split(' ')[0] }}"
  when: md5sum_result.rc == 0

- name: dcn-vsc | _copy_image | save md5sum
  shell: "echo {{ vsc_md5sum }} > /tmp/{{ vsc_image_name }}.md5"
