---

- name: dcn-vsc | _create_virsh_nets |
        Copy the network definition files to the target machine
  become: yes
  template:
    src: "{{ playbook_dir }}/roles/dcn-vsc/templates/{{ item }}.j2"
    dest: /tmp/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - vsc_dcm_vnet.xml
    - vsc_tul_vnet.xml

- name: dcn-vsc | _create_virsh_nets |
        Check if the dcm virtual network is already created
  become: yes
  command: virsh net-info {{ vsc_dcm_virsh_net }}
  register: dcm_vnet_exists_result
  ignore_errors: true

- name: dcn-vsc | _create_virsh_nets | Create the dcm virtual network
  become: yes
  command: virsh net-define /tmp/vsc_dcm_vnet.xml
  when: dcm_vnet_exists_result|failed

- name: dcn-vsc | _create_virsh_nets | Start the dcm virtual network
  become: yes
  command: virsh net-start {{ vsc_dcm_virsh_net }}
  when: dcm_vnet_exists_result|failed

- name: dcn-vsc | _create_virsh_nets | Autostart the dcm virtual network
  become: yes
  command: virsh net-autostart {{ vsc_dcm_virsh_net }}
  when: dcm_vnet_exists_result|failed

- name: dcn-vsc | _create_virsh_nets |
        Check if the tul virtual network is already created
  become: yes
  command: virsh net-info {{ vsc_tul_virsh_net }}
  register: tul_vnet_exists_result
  ignore_errors: true

- name: dcn-vsc | _create_virsh_nets | Create the tul virtual network
  become: yes
  command: virsh net-define /tmp/vsc_tul_vnet.xml
  when: tul_vnet_exists_result|failed

- name: dcn-vsc | _create_virsh_nets | Start the tul virtual network
  become: yes
  command: virsh net-start {{ vsc_tul_virsh_net }}
  when: tul_vnet_exists_result|failed

- name: dcn-vsc | _create_virsh_nets | Autostart the tul virtual network
  become: yes
  command: virsh net-autostart {{ vsc_tul_virsh_net }}
  when: tul_vnet_exists_result|failed
