---

- name: dcn-vsc | _destroy-vsc-vm | undefine the VSC VM
  become: yes
  virt:
    name: "{{ vsc_vm_name }}"
    command: undefine
    uri: "qemu:///system"
  ignore_errors: true

- name: dcn-vsc | _destroy-vsc-vm | delete the files under vsc_image_dir
  become: yes
  shell: rm -f "{{ vsc_image_dir }}/{{ vsc_image_name }}."*
  ignore_errors: true
