---

- name: dcn-vsc | _provision | define vsc vm
  become: yes
  virt:
    name: "{{ vsc_vm_name }}"
    command: define
    xml: "{{ lookup('template', '../templates/vsc.xml.j2') }}"
    uri: "qemu:///system"

- name: dcn-vsc | _provision | start vsc vm
  become: yes
  virt:
    name: "{{ vsc_vm_name }}"
    state: running
    uri: "qemu:///system"
