---

- include: _create_virsh_nets.yml
- include: _provisionvsc.yml

- name: dcn-vsc | deploy | wait for VSC to stabilize
  delegate_to: localhost
  wait_for:
    host: "{{ vsc_dcm_ip }}"
    port: 22
    search_regex: OpenSSH
    delay: "{{ vsc_start_delay }}"
    timeout: "{{ vsc_start_timeout }}"
