---

- name: dcn-vsc | install | set new required_packages to VSC dependencies
  set_fact:
    required_packages: "{{ vsc_dependent_pkgs }}"

# common_install installs dependencies based on ansible_os_family
- include: ../../dcn-common/tasks/common_install.yml
