---

- name: dcn-vsc | status | Print service being checked
  debug:
    msg: "Running service check for DCN VSC"
  run_once: true

- include: _check-vm-status.yml

- name: dcn-vsc | status | Report failure
  fail:
    msg: "VSC VM {{ vsc_vm_name }} is not running"
  when: vm_status|failed or vm_status.status is not defined or
    vm_status.status != 'running'

- name: dcn-vsc | status | Report status on success
  debug:
    msg: "VSC VM {{ vsc_vm_name }} is running"
  when: vm_status|success and vm_status.status is defined and
    vm_status.status == 'running'
