---

- name: dcn-vsc | stop | shut down the VSC VM
  become: yes
  virt:
    name: "{{ vsc_vm_name }}"
    command: destroy
    uri: "qemu:///system"
  ignore_errors: true

- name: dcn-vsc | stop | pausing for VM to be destroyed completely
  pause:
    seconds: 30

- include: _check-vm-status.yml

- name: dcn-vsc | stop | FAILED VSC VM is still running
  fail:
    msg: "VSC VM {{ vsc_vm_name }} is running"
  when: vm_status|success and vm_status.status is defined and
    vm_status.status == 'running'

- name: dcn-vsc | stop | Report VSC VM has shutdown
  debug:
    msg: "VSC VM {{ vsc_vm_name }} is not running"
  when: vm_status|failed or vm_status.status is not defined or
    vm_status.status != 'running'
