---

- include: _check-vm-status.yml

- name: dcn-vsc | vsc-destroy | Display VM status
  debug: var=vm_status

- name: dcn-vsc | vsc-destroy | Decide if the VSC needs to be destroyed
  set_fact:
    destroy_vsc_vm: vm_status|success

- include: _destroy-vsc-vm.yml
  when: destroy_vsc_vm

- include: _destroy_virsh_nets.yml
  when: destroy_vsc_vm
