---

- include: _check-vm-status.yml

- name: dcn-vsc | vsc-deploy | Display VM status
  debug: var=vm_status

- name: dcn-vsc | vsc-deploy | Decide if the VSC should be deployed
  set_fact:
    vsc_vm_needs_deployment: vm_status|failed

- include: install.yml
  when: vsc_vm_needs_deployment

- include: _copy_image.yml
  when: vsc_vm_needs_deployment

- include: image-configure.yml
  when: vsc_vm_needs_deployment

- include: deploy.yml
  when: vsc_vm_needs_deployment

- include: vsc-os-configure.yml
  when: vsc_vm_needs_deployment

- name: dcn-vsc | vsc-deploy | save the new qcow2's md5sum to vsc_image_dir
  become: yes
  command: "cp /tmp/{{ vsc_image_name }}.md5 {{ vsc_image_dir }}"
  when: vsc_vm_needs_deployment
