---

- name: dcn-vsc | vsc-os-configure | run the vsc_ops script on localhost
  local_action: command sh {{ playbook_dir }}/roles/dcn-vsc/files/vsc_ops.sh
                {{ vsc_user_name }}
                {{ vsc_dcm_ip }}
                {{ upstream_ntp_servers[0] }}
                {{ upstream_ntp_servers[1] }}
                {{ vsc_xmpp_name }}
                {{ vsc_tul_ip }}/{{ vsc_tul_ip_subnet }}
                {{ vsc_host_name }}
  environment:
    SSHPASS: '{{ vsc_user_pass }}'
